/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PupApp {
    }
    interface PupList {
        "dogs": string[];
    }
    interface PupPic {
        "dogURL": string;
    }
}
declare global {
    interface HTMLPupAppElement extends Components.PupApp, HTMLStencilElement {
    }
    var HTMLPupAppElement: {
        prototype: HTMLPupAppElement;
        new (): HTMLPupAppElement;
    };
    interface HTMLPupListElement extends Components.PupList, HTMLStencilElement {
    }
    var HTMLPupListElement: {
        prototype: HTMLPupListElement;
        new (): HTMLPupListElement;
    };
    interface HTMLPupPicElement extends Components.PupPic, HTMLStencilElement {
    }
    var HTMLPupPicElement: {
        prototype: HTMLPupPicElement;
        new (): HTMLPupPicElement;
    };
    interface HTMLElementTagNameMap {
        "pup-app": HTMLPupAppElement;
        "pup-list": HTMLPupListElement;
        "pup-pic": HTMLPupPicElement;
    }
}
declare namespace LocalJSX {
    interface PupApp {
    }
    interface PupList {
        "dogs"?: string[];
    }
    interface PupPic {
        "dogURL"?: string;
    }
    interface IntrinsicElements {
        "pup-app": PupApp;
        "pup-list": PupList;
        "pup-pic": PupPic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pup-app": LocalJSX.PupApp & JSXBase.HTMLAttributes<HTMLPupAppElement>;
            "pup-list": LocalJSX.PupList & JSXBase.HTMLAttributes<HTMLPupListElement>;
            "pup-pic": LocalJSX.PupPic & JSXBase.HTMLAttributes<HTMLPupPicElement>;
        }
    }
}
